//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWIC.FinalProject.Common.svcUpdateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcUpdateService.IWebBrowserUpdateService")]
    public interface IWebBrowserUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebBrowserUpdateService/CheckForUpdates", ReplyAction="http://tempuri.org/IWebBrowserUpdateService/CheckForUpdatesResponse")]
        System.Collections.Generic.Dictionary<string, object> CheckForUpdates(System.Version currentVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebBrowserUpdateService/CheckForUpdates", ReplyAction="http://tempuri.org/IWebBrowserUpdateService/CheckForUpdatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> CheckForUpdatesAsync(System.Version currentVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebBrowserUpdateServiceChannel : UWIC.FinalProject.Common.svcUpdateService.IWebBrowserUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebBrowserUpdateServiceClient : System.ServiceModel.ClientBase<UWIC.FinalProject.Common.svcUpdateService.IWebBrowserUpdateService>, UWIC.FinalProject.Common.svcUpdateService.IWebBrowserUpdateService {
        
        public WebBrowserUpdateServiceClient() {
        }
        
        public WebBrowserUpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebBrowserUpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebBrowserUpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebBrowserUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, object> CheckForUpdates(System.Version currentVersion) {
            return base.Channel.CheckForUpdates(currentVersion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> CheckForUpdatesAsync(System.Version currentVersion) {
            return base.Channel.CheckForUpdatesAsync(currentVersion);
        }
    }
}
